name: Deploy App to S3

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch
permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x  # Specify the Node.js version

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build the Next.js app
        run: pnpm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          # https://github.com/aws-actions/configure-aws-credentials/issues/402
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Sync files to S3
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          aws s3 sync ./out s3://$S3_BUCKET_NAME
      - name: Invalidate cache
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
        run: |
          aws cloudfront create-invalidation  --distribution-id $DISTRIBUTION --paths "/index.html"
